/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TButton, TColor, TSize, } from "./components/btn-tutator/types";
export namespace Components {
    interface BtnTutator {
        "color": TColor;
        "label": string;
        "size": TSize;
        "type": TButton;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBtnTutatorElement extends Components.BtnTutator, HTMLStencilElement {
    }
    var HTMLBtnTutatorElement: {
        prototype: HTMLBtnTutatorElement;
        new (): HTMLBtnTutatorElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "btn-tutator": HTMLBtnTutatorElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BtnTutator {
        "color"?: TColor;
        "label"?: string;
        "size"?: TSize;
        "type"?: TButton;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "btn-tutator": BtnTutator;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "btn-tutator": LocalJSX.BtnTutator & JSXBase.HTMLAttributes<HTMLBtnTutatorElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
